spring:
    profiles:
        active: swagger,dev
    application:
        name: yche


# jwt配置
jwt:
    auth-header: Authorization
    expiredIn: 120
    refreshIn: 10080
    secret: yche4

logging:
    level:
        ROOT: info