server:
    port: 8888
    ssl:
        key-store: "classpath:keystore.jks"
        key-store-password: "123456"
        key-password: "123456"

swagger:
    enabled: true
    title: "学习shiro+jwt接口文档"
    version: "1.0"
    contact:
        name: "hyc"
        email: "yche.com"
    base-package: "com.hyc.controller"
